id: P008172
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22946
  title: གཏམ་རྒྱུད།
  author: ''
  volumes:
    56dc7e1456d14cddb543cc49a7173b1d:
      image_group_id: I1KG23008
      title: ''
      volume_number: 1
      total_pages: 578
      base_file: v001.txt
